# [[rulesets]]
# group = "[groupname]"
# ruleset = "URL"
# type = "surge-ruleset"
# interval = 86400
#
# supported type: surge-ruleset, quantumultx, clash-domain, clash-ipcidr, clash-classic
# default type: surge-ruleset

# å¹¿å‘Šæ‹¦æˆª:
# å¹¿å‘Šæ‹¦æˆª-è§„åˆ™ä¿®æ­£ é…åˆç²¾ç®€
[[rulesets]]
group = "ğŸ¯ å…¨éƒ¨ç›´è¿"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Direct/Direct.yaml"
type = "clash-classic"

# å¹¿å‘Šæ‹¦æˆª-ç²¾ç®€
[[rulesets]]
group = "ğŸ›‘ å…¨éƒ¨æ‹¦æˆª"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/AdvertisingLite/AdvertisingLite_Classical.yaml"
type = "clash-classic"

# # éšç§ä¿æŠ¤ (å¹¿å‘Šæ‹¦æˆªå·²åŒ…å«)
# [[rulesets]]
# group = "ğŸ›‘ å…¨éƒ¨æ‹¦æˆª"
# ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Privacy/Privacy_Classical.yaml"
# type = "clash-classic"

# # ååŠ«æŒ (å¹¿å‘Šæ‹¦æˆªå·²åŒ…å«)
# [[rulesets]]
# group = "ğŸ›‘ å…¨éƒ¨æ‹¦æˆª"
# ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Hijacking/Hijacking.yaml"
# type = "clash-classic"
