# [[rulesets]]
# group = "[groupname]"
# ruleset = "URL"
# type = "surge-ruleset"
# interval = 86400
#
# supported type: surge-ruleset, quantumultx, clash-domain, clash-ipcidr, clash-classic
# default type: surge-ruleset

# ç»•è¿‡å±€åŸŸç½‘
[[rulesets]]
group = "ðŸŽ¯ å…¨éƒ¨ç›´è¿ž"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Lan/Lan.yaml"
type = "clash-classic"

# ç»•è¿‡ BT ä¸Žä¸‹è½½å™¨
[[rulesets]]
group = "ðŸŽ¯ å…¨éƒ¨ç›´è¿ž"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Download/Download.yaml"
type = "clash-classic"

# ç»•è¿‡ PT
[[rulesets]]
group = "ðŸŽ¯ å…¨éƒ¨ç›´è¿ž"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/PrivateTracker/PrivateTracker.yaml"
type = "clash-classic"