# [[rulesets]]
# group = "[groupname]"
# ruleset = "URL"
# type = "surge-ruleset"
# interval = 86400
#
# supported type: surge-ruleset, quantumultx, clash-domain, clash-ipcidr, clash-classic
# default type: surge-ruleset

# Ondrive
[[rulesets]]
group = "â˜ï¸ Onedrive"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OneDrive/OneDrive.yaml"
type = "clash-classic"

# å¾®è½¯æœåŠ¡
[[rulesets]]
group = "â“‚ï¸ å¾®è½¯æœåŠ¡"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Microsoft/Microsoft.yaml"
type = "clash-classic"

# # Google Voice
# [[rulesets]]
# group = "ğŸ“ è™šæ‹Ÿç”µè¯"
# ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GoogleVoice/GoogleVoice.yaml"
# type = "clash-classic"

# è°·æ­ŒæœåŠ¡
[[rulesets]]
group = "ğŸ­ è°·æ­ŒæœåŠ¡"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Google/Google.yaml"
type = "clash-classic"

# Apple æœåŠ¡
[[rulesets]]
group = "ğŸ è‹¹æœæœåŠ¡"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Apple/Apple.yaml"
type = "clash-classic"

# æ¸¸æˆå¹³å°:
# SteamCN ç›´è¿è§„åˆ™
[[rulesets]]
group = "ğŸ¯ å…¨éƒ¨ç›´è¿"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/SteamCN/SteamCN.yaml"
type = "clash-classic"
# Steam ä»£ç†è§„åˆ™
[[rulesets]]
group = "ğŸ® Steam"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Steam/Steam.yaml"
type = "clash-classic"

# # Origin
# [[rulesets]]
# group = "ğŸ® Origin"
# ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Origin/Origin.yaml"
# type = "clash-classic"

# # UBI
# [[rulesets]]
# group = "ğŸ® Ubi"
# ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/UBI/UBI.yaml"
# type = "clash-classic"

# # Epic
# [[rulesets]]
# group = "ğŸ® Epic"
# ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Epic/Epic.yaml"
# type = "clash-classic"

# # æ¸¸æˆå¹³å°-æ€»
# [[rulesets]]
# group = "ğŸ® æ¸¸æˆå¹³å°"
# ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Game/Game.yaml"
# type = "clash-classic"

# æµåª’ä½“å¹³å°ï¼š
# Spotify
[[rulesets]]
group = "ğŸµ Spotify"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Spotify/Spotify.yaml"
type = "clash-classic"

# Qobuz
[[rulesets]]
group = "ğŸµ Qobuz"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Qobuz/Qobuz.yaml"
type = "clash-classic"

# TIDAL
[[rulesets]]
group = "ğŸµ TIDAL"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/TIDAL/TIDAL.yaml"
type = "clash-classic"

# Youtube
[[rulesets]]
group = "ğŸ¥ Youtube"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/YouTube/YouTube.yaml"
type = "clash-classic"

# Netflix
[[rulesets]]
group = "ğŸ¥ Netflix"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Netflix/Netflix.yaml"
type = "clash-classic"

# TikTok
[[rulesets]]
group = "ğŸ¥ TikTok"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/TikTok/TikTok.yaml"
type = "clash-classic"

# å›½å¤–åª’ä½“
[[rulesets]]
group = "ğŸŒ å›½å¤–åª’ä½“"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GlobalMedia/GlobalMedia.yaml"
type = "clash-classic"

# ç½‘æ˜“äº‘éŸ³ä¹
[[rulesets]]
group = "ğŸµ ç½‘æ˜“äº‘éŸ³ä¹"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/NetEaseMusic/NetEaseMusic.yaml"
type = "clash-classic"

# ğŸŒ å›½å†…åª’ä½“-æ¸¯æ¾³å°ç‰ˆåˆ‡æ¢
[[rulesets]]
group = "ğŸŒ å›½å†…åª’ä½“-æ¸¯æ¾³å°ç‰ˆåˆ‡æ¢"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/AsianMedia/AsianMedia.yaml"
type = "clash-classic"

# å›½å†…åª’ä½“
[[rulesets]]
group = "ğŸŒ å›½å†…åª’ä½“"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/ChinaMedia/ChinaMedia.yaml"
type = "clash-classic"

# Telegram
[[rulesets]]
group = "ğŸ“² Telegram"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Telegram/Telegram.yaml"
type = "clash-classic"

# Twitter
[[rulesets]]
group = "ğŸ“² Twitter"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Twitter/Twitter.yaml"
type = "clash-classic"

# é»˜è®¤ä»£ç†å›½å¤–
[[rulesets]]
group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Global/Global_Classical.yaml"
type = "clash-classic"

# ç»•è¿‡ä¸­å›½å¤§é™†
[[rulesets]]
group = "ğŸ¯ å…¨éƒ¨ç›´è¿"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/China/China.yaml"
type = "clash-classic"

[[rulesets]]
group = "ğŸ¯ å…¨éƒ¨ç›´è¿"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/ChinaIPs/ChinaIPs_Classical.yaml"
type = "clash-classic"

# [[rulesets]]
# group = "ğŸ¯ å…¨éƒ¨ç›´è¿"
# ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/ChinaIPsBGP/ChinaIPsBGP_Classical.yaml"
# type = "clash-classic"

# ç»•è¿‡ä¸­å›½ IP
[[rulesets]]
group = "ğŸ¯ å…¨éƒ¨ç›´è¿"
ruleset = "[]GEOIP,CN"

# å…œåº•ç­–ç•¥
[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"

