# [[custom_groups]]
# name = "🍭 服务名称"
# type = "select"
# rule = [
#     "[]✈️ 手动选择",
#     "[]🔰 节点选择",
#     "[]🎯 全部直连",
#     "[]🇭🇰 香港接入",
#     "[]🇺🇸 美国接入",
#     "[]🇯🇵 日本接入",
#     "[]🇨🇳 台湾接入",
#     "[]🇸🇬 新加坡接入",
#     "[]🇰🇷 韩国接入",
# ]

# [[custom_groups]]
# name = "♻️ 自动选择"
# type = "url-test"
# rule = [".*"]
# url = "http://www.gstatic.com/generate_204"
# interval = 300

# Main Selectors
[[custom_groups]]
name = "🔰 节点选择"
type = "select"
rule = [
    "[]🎯 全部直连",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
]

[[custom_groups]]
name = "✈️ 手动选择"
type = "select"
rule = [
    ".*",
]

[[custom_groups]]
name = "🍭 谷歌服务"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]🎯 全部直连",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
]

[[custom_groups]]
name = "Ⓜ️ 微软服务"
type = "select"
rule = [
    "[]🎯 全部直连",
    "[]🔰 节点选择",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
]

[[custom_groups]]
name = "☁️ Onedrive"
type = "select"
rule = [
    "[]Ⓜ️ 微软服务",
    "[]🎯 全部直连",
    "[]🔰 节点选择",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
]

[[custom_groups]]
name = "🍎 苹果服务"
type = "select"
rule = [
    "[]🎯 全部直连",
    "[]🔰 节点选择",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
]

[[custom_groups]]
name = "🎮 Steam"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]🎯 全部直连",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
]

# [[custom_groups]]
# name = "🎮 游戏平台"
# type = "select"
# rule = [
#     "[]🔰 节点选择",
#     "[]🎯 全部直连",
#     "[]✈️ 手动选择",
#     "[]🇭🇰 香港接入",
#     "[]🇺🇸 美国接入",
#     "[]🇯🇵 日本接入",
#     "[]🇨🇳 台湾接入",
#     "[]🇸🇬 新加坡接入",
#     "[]🇰🇷 韩国接入",
# ]

[[custom_groups]]
name = "🎵 Spotify"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]🎯 全部直连",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
]

[[custom_groups]]
name = "🎵 Qobuz"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]🎯 全部直连",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
]

[[custom_groups]]
name = "🎵 TIDAL"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]🎯 全部直连",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
]

[[custom_groups]]
name = "🎥 Youtube"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]🎯 全部直连",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
]

[[custom_groups]]
name = "🎥 Netflix"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]🎯 全部直连",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
]

[[custom_groups]]
name = "🎥 TikTok"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]🎯 全部直连",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
]

[[custom_groups]]
name = "🌍 国外媒体"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]🎯 全部直连",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
]

[[custom_groups]]
name = "🎵 网易云音乐"
type = "select"
rule = [
    "[]🎯 全部直连",
    "[]🔰 节点选择",
    "[]✈️ 手动选择",
]

[[custom_groups]]
name = "🌍 国内媒体-港澳台版切换"
type = "select"
rule = [
    "[]🌏 国内媒体",
    "[]🎯 全部直连",
    "[]🔰 节点选择",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
]

[[custom_groups]]
name = "🌏 国内媒体"
type = "select"
rule = [
    "[]🎯 全部直连",
    "[]🔰 节点选择",
    "[]✈️ 手动选择",
]

[[custom_groups]]
name = "📲 Telegram"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]🎯 全部直连",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
]

[[custom_groups]]
name = "📲 Twitter"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]🎯 全部直连",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
]

# [[custom_groups]]
# name = "📞 虚拟电话"
# type = "select"
# rule = [
#     "[]🎯 全部直连",
#     "[]🔰 节点选择",
#     "[]✈️ 手动选择",
#     "[]🇭🇰 香港接入",
#     "[]🇺🇸 美国接入",
#     "[]🇯🇵 日本接入",
#     "[]🇨🇳 台湾接入",
#     "[]🇸🇬 新加坡接入",
#     "[]🇰🇷 韩国接入",
# ]

[[custom_groups]]
name = "🎯 全部直连"
type = "select"
rule = ["[]DIRECT"]

[[custom_groups]]
name = "🛑 全部拦截"
type = "select"
rule = ["[]REJECT"]

[[custom_groups]]
name = "🐟 漏网之鱼"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]🎯 全部直连",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
]

# Areas Nodes Select Groups
[[custom_groups]]
name = "🇭🇰 香港接入"
type = "select"
rule = [
    "(?i:\\bHK[G]?\\b|Hong.*?Kong|\\bHKT\\b|\\bHKBN\\b|\\bHGC\\b|\\bWTT\\b|\\bCMI\\b|[^-]港)",
]

[[custom_groups]]
name = "🇺🇸 美国接入"
type = "select"
rule = [
    "(?i:\\bUS[A]?\\b|America|United.*?States|美国|[^-]美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥)",
]

[[custom_groups]]
name = "🇯🇵 日本接入"
type = "select"
rule = [
    "(?i:\\bJP[N]?\\b|Japan|Tokyo|Osaka|Saitama|日本|东京|大阪|埼玉|[^-]日)",
]

[[custom_groups]]
name = "🇨🇳 台湾接入"
type = "select"
rule = [
    "(?i:\\bTW[N]?\\b|Taiwan|新北|彰化|\\bCHT\\b|台湾|[^-]台|\\bHINET\\b)",
]

[[custom_groups]]
name = "🇸🇬 新加坡接入"
type = "select"
rule = [
    "(?i:\\bSG[P]?\\b|Singapore|新加坡|狮城|[^-]新)",
]

[[custom_groups]]
name = "🇰🇷 韩国接入"
type = "select"
rule = [
    "(?i:\\bK[O]?R\\b|Korea|首尔|韩|韓)",
]
