# [[custom_groups]]
# name = "ğŸ­ æœåŠ¡åç§°"
# type = "select"
# rule = [
#     "[]âœˆï¸ æ‰‹åŠ¨é€‰æ‹©",
#     "[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
#     "[]ğŸ¯ å…¨éƒ¨ç›´è¿",
#     "[]ğŸ‡­ğŸ‡° é¦™æ¸¯æ¥å…¥",
#     "[]ğŸ‡ºğŸ‡¸ ç¾å›½æ¥å…¥",
#     "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬æ¥å…¥",
#     "[]ğŸ‡¨ğŸ‡³ å°æ¹¾æ¥å…¥",
#     "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡æ¥å…¥",
#     "[]ğŸ‡°ğŸ‡· éŸ©å›½æ¥å…¥",
#     "[]ğŸ‡®ğŸ‡³ å°åº¦æ¥å…¥",
#     "[]ğŸ‡¬ğŸ‡§ è‹±å›½æ¥å…¥",
#     "[]ğŸ‡«ğŸ‡· æ³•å›½æ¥å…¥",
#     "[]ğŸ‡¨ğŸ‡¦ åŠ æ‹¿å¤§æ¥å…¥",
#     "[]ğŸ‡¦ğŸ‡º æ¾³å¤§åˆ©äºšæ¥å…¥",
#     "[]ğŸ‡®ğŸ‡ª çˆ±å°”å…°æ¥å…¥",
#     "[]ğŸ‡·ğŸ‡º ä¿„ç½—æ–¯æ¥å…¥",
#     "[]ğŸ‡¹ğŸ‡· åœŸè€³å…¶æ¥å…¥",
#     "[]ğŸ‡¦ğŸ‡· é˜¿æ ¹å»·æ¥å…¥",
#     "[]ğŸ‡§ğŸ‡· å·´è¥¿æ¥å…¥",
#     "[]ğŸ³ï¸â€ğŸŒˆ IPV6çº¿è·¯",
#     "[]ğŸ‡¨ğŸ‡³ å›å›½çº¿è·¯",
# ]

# [[custom_groups]]
# name = "â™»ï¸ è‡ªåŠ¨é€‰æ‹©"
# type = "url-test"
# rule = [".*"]
# url = "http://www.gstatic.com/generate_204"
# interval = 300

# Areas Nodes Select Groups
[[custom_groups]]
name = "ğŸ‡­ğŸ‡° é¦™æ¸¯æ¥å…¥"
type = "select"
rule = [
    "(?i:\\bHK[G]?\\b|Hong.*?Kong|\\bHKT\\b|\\bHKBN\\b|\\bHGC\\b|\\bWTT\\b|\\bCMI\\b|[^-]æ¸¯)",
]

[[custom_groups]]
name = "ğŸ‡ºğŸ‡¸ ç¾å›½æ¥å…¥"
type = "select"
rule = [
    "(?i:\\bUS[A]?\\b|America|United.*?States|ç¾å›½|[^-]ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥)",
]

[[custom_groups]]
name = "ğŸ‡¯ğŸ‡µ æ—¥æœ¬æ¥å…¥"
type = "select"
rule = [
    "(?i:\\bJP[N]?\\b|Japan|Tokyo|Osaka|Saitama|æ—¥æœ¬|ä¸œäº¬|å¤§é˜ª|åŸ¼ç‰|[^-]æ—¥)",
]

[[custom_groups]]
name = "ğŸ‡¨ğŸ‡³ å°æ¹¾æ¥å…¥"
type = "select"
rule = [
    "(?i:\\bTW[N]?\\b|Taiwan|æ–°åŒ—|å½°åŒ–|\\bCHT\\b|å°æ¹¾|[^-]å°|\\bHINET\\b)",
]

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡æ¥å…¥"
type = "select"
rule = [
    "(?i:\\bSG[P]?\\b|Singapore|æ–°åŠ å¡|ç‹®åŸ|[^-]æ–°)",
]

[[custom_groups]]
name = "ğŸ‡°ğŸ‡· éŸ©å›½æ¥å…¥"
type = "select"
rule = [
    "(?i:\\bK[O]?R\\b|Korea|é¦–å°”|éŸ©|éŸ“)",
]

[[custom_groups]]
name = "ğŸ‡®ğŸ‡³ å°åº¦æ¥å…¥"
type = "select"
rule = [
    "(?i:\\bIN[D]?\\b|India|Mumbai|å°åº¦|å­Ÿä¹°|åŠ å°”å„ç­”|è´¾åå¾·|æ³°ç±³å°”çº³å¾·)",
]

[[custom_groups]]
name = "ğŸ‡¬ğŸ‡§ è‹±å›½æ¥å…¥"
type = "select"
rule = [
    "(?i:\\bUK\\b|\\bGB[R]?\\b|England|United.*?Kingdom|London|è‹±å›½|[^-]è‹±|ä¼¦æ•¦)",
]

[[custom_groups]]
name = "ğŸ‡«ğŸ‡· æ³•å›½æ¥å…¥"
type = "select"
rule = [
    "(?i:\\bFR[A]?\\b|France|Paris|æ³•å›½|å·´é»)",
]

[[custom_groups]]
name = "ğŸ‡¨ğŸ‡¦ åŠ æ‹¿å¤§æ¥å…¥"
type = "select"
rule = [
    "(?i:\\bCA[N]?\\b|Canada|Toronto|Montreal|Vancouver|åŠ æ‹¿å¤§|è’™ç‰¹åˆ©å°”|æ¸©å“¥å|æ¥“è‘‰|æ«å¶)",
]

[[custom_groups]]
name = "ğŸ‡¦ğŸ‡º æ¾³å¤§åˆ©äºšæ¥å…¥"
type = "select"
rule = [
    "(?i:\\bAU[S]?\\b|Australia|Sydney|æ¾³å¤§åˆ©äºš|æ¾³æ´²|æ‚‰å°¼)",
]

[[custom_groups]]
name = "ğŸ‡®ğŸ‡ª çˆ±å°”å…°æ¥å…¥"
type = "select"
rule = [
    "(Ireland|Dublin|çˆ±å°”å…°|éƒ½æŸæ—)",
]

[[custom_groups]]
name = "ğŸ‡·ğŸ‡º ä¿„ç½—æ–¯æ¥å…¥"
type = "select"
rule = [
    "(?i:\\bRU[S]?\\b|Russia|Moscow|Petersburg|Siberia|ä¼¯åŠ›|è«æ–¯ç§‘|åœ£å½¼å¾—å ¡|è¥¿ä¼¯åˆ©äºš|æ–°è¥¿ä¼¯åˆ©äºš|å“ˆå·´ç½—å¤«æ–¯å…‹|ä¿„ç½—æ–¯|[^-]ä¿„)",
]

[[custom_groups]]
name = "ğŸ‡¹ğŸ‡· åœŸè€³å…¶æ¥å…¥"
type = "select"
rule = [
    "(Turkey|åœŸè€³å…¶|ä¼Šæ–¯å¦å¸ƒå°”)",
]

[[custom_groups]]
name = "ğŸ‡¦ğŸ‡· é˜¿æ ¹å»·æ¥å…¥"
type = "select"
rule = [
    "(Argentina|é˜¿æ ¹å»·)",
]

[[custom_groups]]
name = "ğŸ‡§ğŸ‡· å·´è¥¿æ¥å…¥"
type = "select"
rule = [
    "(Brazil|Paulo|å·´è¥¿|åœ£ä¿ç½—)",
]

[[custom_groups]]
name = "ğŸ³ï¸â€ğŸŒˆ IPV6çº¿è·¯"
type = "select"
rule = [
    "(ipv6|IPV6)",
]

[[custom_groups]]
name = "ğŸ‡¨ğŸ‡³ å›å›½çº¿è·¯"
type = "select"
rule = [
    "(?i:\\bC[H]?N\\b|China|å›å›½|ä¸­å›½[^-]|æ±Ÿè‹[^-]|åŒ—äº¬[^-]|ä¸Šæµ·[^-]|å¹¿å·[^-]|æ·±åœ³[^-]|æ­å·[^-]|å¸¸å·[^-]|å¾å·[^-]|é’å²›[^-]|å®æ³¢[^-]|é•‡æ±Ÿ[^-]|æˆéƒ½[^-]|back)",
]
