# [[custom_groups]]
# name = "ğŸ­ æœåŠ¡åç§°"
# type = "select"
# rule = [
#     "[]âœˆï¸ æ‰‹åŠ¨é€‰æ‹©",
#     "[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
#     "[]ğŸ¯ å…¨éƒ¨ç›´è¿",
#     "[]ğŸ‡­ğŸ‡° é¦™æ¸¯æ¥å…¥",
#     "[]ğŸ‡ºğŸ‡¸ ç¾å›½æ¥å…¥",
#     "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬æ¥å…¥",
#     "[]ğŸ‡¨ğŸ‡³ å°æ¹¾æ¥å…¥",
#     "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡æ¥å…¥",
#     "[]ğŸ‡°ğŸ‡· éŸ©å›½æ¥å…¥",
# ]

# [[custom_groups]]
# name = "â™»ï¸ è‡ªåŠ¨é€‰æ‹©"
# type = "url-test"
# rule = [".*"]
# url = "http://www.gstatic.com/generate_204"
# interval = 300

# Areas Nodes Select Groups
[[custom_groups]]
name = "ğŸ‡­ğŸ‡° é¦™æ¸¯æ¥å…¥"
type = "url-test"
rule = [
    "(?i:\\bHK[G]?\\b|Hong.*?Kong|\\bHKT\\b|\\bHKBN\\b|\\bHGC\\b|\\bWTT\\b|\\bCMI\\b|[^-]æ¸¯)",
]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡ºğŸ‡¸ ç¾å›½æ¥å…¥"
type = "url-test"
rule = [
    "(?i:\\bUS[A]?\\b|America|United.*?States|ç¾å›½|[^-]ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥)",
]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡¯ğŸ‡µ æ—¥æœ¬æ¥å…¥"
type = "url-test"
rule = [
    "(?i:\\bJP[N]?\\b|Japan|Tokyo|Osaka|Saitama|æ—¥æœ¬|ä¸œäº¬|å¤§é˜ª|åŸ¼ç‰|[^-]æ—¥)",
]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡¨ğŸ‡³ å°æ¹¾æ¥å…¥"
type = "url-test"
rule = [
    "(?i:\\bTW[N]?\\b|Taiwan|æ–°åŒ—|å½°åŒ–|\\bCHT\\b|å°æ¹¾|[^-]å°|\\bHINET\\b)",
]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡æ¥å…¥"
type = "url-test"
rule = [
    "(?i:\\bSG[P]?\\b|Singapore|æ–°åŠ å¡|ç‹®åŸ|[^-]æ–°)",
]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡°ğŸ‡· éŸ©å›½æ¥å…¥"
type = "url-test"
rule = [
    "(?i:\\bK[O]?R\\b|Korea|é¦–å°”|éŸ©|éŸ“)",
]
url = "http://www.gstatic.com/generate_204"
interval = 300
