# [[custom_groups]]
# name = "🍭 服务名称"
# type = "select"
# rule = [
#     "[]✈️ 手动选择",
#     "[]🔰 节点选择",
#     "[]🎯 全部直连",
#     "[]🇭🇰 香港接入",
#     "[]🇺🇸 美国接入",
#     "[]🇯🇵 日本接入",
#     "[]🇨🇳 台湾接入",
#     "[]🇸🇬 新加坡接入",
#     "[]🇰🇷 韩国接入",
#     "[]🇮🇳 印度接入",
#     "[]🇬🇧 英国接入",
#     "[]🇫🇷 法国接入",
#     "[]🇨🇦 加拿大接入",
#     "[]🇦🇺 澳大利亚接入",
#     "[]🇮🇪 爱尔兰接入",
#     "[]🇷🇺 俄罗斯接入",
#     "[]🇹🇷 土耳其接入",
#     "[]🇦🇷 阿根廷接入",
#     "[]🇧🇷 巴西接入",
#     "[]🏳️‍🌈 IPV6线路",
#     "[]🇨🇳 回国线路",
# ]

# [[custom_groups]]
# name = "♻️ 自动选择"
# type = "url-test"
# rule = [".*"]
# url = "http://www.gstatic.com/generate_204"
# interval = 300

# Main proxy groups
[[custom_groups]]
name = "🔰 节点选择"
type = "select"
rule = [
    "[]🎯 全部直连",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
    "[]🇮🇳 印度接入",
    "[]🇬🇧 英国接入",
    "[]🇫🇷 法国接入",
    "[]🇨🇦 加拿大接入",
    "[]🇦🇺 澳大利亚接入",
    "[]🇮🇪 爱尔兰接入",
    "[]🇷🇺 俄罗斯接入",
    "[]🇹🇷 土耳其接入",
    "[]🇦🇷 阿根廷接入",
    "[]🇧🇷 巴西接入",
    "[]🏳️‍🌈 IPV6线路",
    "[]🇨🇳 回国线路",
]

[[custom_groups]]
name = "✈️ 手动选择"
type = "select"
rule = [
    ".*",
]

[[custom_groups]]
name = "🍭 谷歌服务"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]🎯 全部直连",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
    "[]🇮🇳 印度接入",
    "[]🇬🇧 英国接入",
    "[]🇫🇷 法国接入",
    "[]🇨🇦 加拿大接入",
    "[]🇦🇺 澳大利亚接入",
    "[]🇮🇪 爱尔兰接入",
    "[]🇷🇺 俄罗斯接入",
    "[]🇹🇷 土耳其接入",
    "[]🇦🇷 阿根廷接入",
    "[]🇧🇷 巴西接入",
    "[]🏳️‍🌈 IPV6线路",
    "[]🇨🇳 回国线路",
]

[[custom_groups]]
name = "Ⓜ️ 微软服务"
type = "select"
rule = [
    "[]🎯 全部直连",
    "[]🔰 节点选择",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
    "[]🇮🇳 印度接入",
    "[]🇬🇧 英国接入",
    "[]🇫🇷 法国接入",
    "[]🇨🇦 加拿大接入",
    "[]🇦🇺 澳大利亚接入",
    "[]🇮🇪 爱尔兰接入",
    "[]🇷🇺 俄罗斯接入",
    "[]🇹🇷 土耳其接入",
    "[]🇦🇷 阿根廷接入",
    "[]🇧🇷 巴西接入",
    "[]🏳️‍🌈 IPV6线路",
    "[]🇨🇳 回国线路",
]

[[custom_groups]]
name = "☁️ Onedrive"
type = "select"
rule = [
    "[]Ⓜ️ 微软服务",
    "[]🎯 全部直连",
    "[]🔰 节点选择",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
    "[]🇮🇳 印度接入",
    "[]🇬🇧 英国接入",
    "[]🇫🇷 法国接入",
    "[]🇨🇦 加拿大接入",
    "[]🇦🇺 澳大利亚接入",
    "[]🇮🇪 爱尔兰接入",
    "[]🇷🇺 俄罗斯接入",
    "[]🇹🇷 土耳其接入",
    "[]🇦🇷 阿根廷接入",
    "[]🇧🇷 巴西接入",
    "[]🏳️‍🌈 IPV6线路",
    "[]🇨🇳 回国线路",
]

[[custom_groups]]
name = "🍎 苹果服务"
type = "select"
rule = [
    "[]🎯 全部直连",
    "[]🔰 节点选择",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
    "[]🇮🇳 印度接入",
    "[]🇬🇧 英国接入",
    "[]🇫🇷 法国接入",
    "[]🇨🇦 加拿大接入",
    "[]🇦🇺 澳大利亚接入",
    "[]🇮🇪 爱尔兰接入",
    "[]🇷🇺 俄罗斯接入",
    "[]🇹🇷 土耳其接入",
    "[]🇦🇷 阿根廷接入",
    "[]🇧🇷 巴西接入",
    "[]🏳️‍🌈 IPV6线路",
    "[]🇨🇳 回国线路",
]

[[custom_groups]]
name = "🎮 Steam"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]🎯 全部直连",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
    "[]🇮🇳 印度接入",
    "[]🇬🇧 英国接入",
    "[]🇫🇷 法国接入",
    "[]🇨🇦 加拿大接入",
    "[]🇦🇺 澳大利亚接入",
    "[]🇮🇪 爱尔兰接入",
    "[]🇷🇺 俄罗斯接入",
    "[]🇹🇷 土耳其接入",
    "[]🇦🇷 阿根廷接入",
    "[]🇧🇷 巴西接入",
    "[]🏳️‍🌈 IPV6线路",
    "[]🇨🇳 回国线路",
]

# [[custom_groups]]
# name = "🎮 游戏平台"
# type = "select"
# rule = [
#     "[]🔰 节点选择",
#     "[]🎯 全部直连",
#     "[]✈️ 手动选择",
#     "[]🇭🇰 香港接入",
#     "[]🇺🇸 美国接入",
#     "[]🇯🇵 日本接入",
#     "[]🇨🇳 台湾接入",
#     "[]🇸🇬 新加坡接入",
#     "[]🇰🇷 韩国接入",
#     "[]🇮🇳 印度接入",
#     "[]🇬🇧 英国接入",
#     "[]🇫🇷 法国接入",
#     "[]🇨🇦 加拿大接入",
#     "[]🇦🇺 澳大利亚接入",
#     "[]🇮🇪 爱尔兰接入",
#     "[]🇷🇺 俄罗斯接入",
#     "[]🇹🇷 土耳其接入",
#     "[]🇦🇷 阿根廷接入",
#     "[]🇧🇷 巴西接入",
#     "[]🏳️‍🌈 IPV6线路",
#     "[]🇨🇳 回国线路",
# ]

[[custom_groups]]
name = "🎵 Spotify"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]🎯 全部直连",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
    "[]🇮🇳 印度接入",
    "[]🇬🇧 英国接入",
    "[]🇫🇷 法国接入",
    "[]🇨🇦 加拿大接入",
    "[]🇦🇺 澳大利亚接入",
    "[]🇮🇪 爱尔兰接入",
    "[]🇷🇺 俄罗斯接入",
    "[]🇹🇷 土耳其接入",
    "[]🇦🇷 阿根廷接入",
    "[]🇧🇷 巴西接入",
    "[]🏳️‍🌈 IPV6线路",
    "[]🇨🇳 回国线路",
]

[[custom_groups]]
name = "🎵 Qobuz"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]🎯 全部直连",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
    "[]🇮🇳 印度接入",
    "[]🇬🇧 英国接入",
    "[]🇫🇷 法国接入",
    "[]🇨🇦 加拿大接入",
    "[]🇦🇺 澳大利亚接入",
    "[]🇮🇪 爱尔兰接入",
    "[]🇷🇺 俄罗斯接入",
    "[]🇹🇷 土耳其接入",
    "[]🇦🇷 阿根廷接入",
    "[]🇧🇷 巴西接入",
    "[]🏳️‍🌈 IPV6线路",
    "[]🇨🇳 回国线路",
]

[[custom_groups]]
name = "🎵 TIDAL"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]🎯 全部直连",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
    "[]🇮🇳 印度接入",
    "[]🇬🇧 英国接入",
    "[]🇫🇷 法国接入",
    "[]🇨🇦 加拿大接入",
    "[]🇦🇺 澳大利亚接入",
    "[]🇮🇪 爱尔兰接入",
    "[]🇷🇺 俄罗斯接入",
    "[]🇹🇷 土耳其接入",
    "[]🇦🇷 阿根廷接入",
    "[]🇧🇷 巴西接入",
    "[]🏳️‍🌈 IPV6线路",
    "[]🇨🇳 回国线路",
]

[[custom_groups]]
name = "🎥 Youtube"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]🎯 全部直连",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
    "[]🇮🇳 印度接入",
    "[]🇬🇧 英国接入",
    "[]🇫🇷 法国接入",
    "[]🇨🇦 加拿大接入",
    "[]🇦🇺 澳大利亚接入",
    "[]🇮🇪 爱尔兰接入",
    "[]🇷🇺 俄罗斯接入",
    "[]🇹🇷 土耳其接入",
    "[]🇦🇷 阿根廷接入",
    "[]🇧🇷 巴西接入",
    "[]🏳️‍🌈 IPV6线路",
    "[]🇨🇳 回国线路",
]

[[custom_groups]]
name = "🎥 Netflix"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]🎯 全部直连",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
    "[]🇮🇳 印度接入",
    "[]🇬🇧 英国接入",
    "[]🇫🇷 法国接入",
    "[]🇨🇦 加拿大接入",
    "[]🇦🇺 澳大利亚接入",
    "[]🇮🇪 爱尔兰接入",
    "[]🇷🇺 俄罗斯接入",
    "[]🇹🇷 土耳其接入",
    "[]🇦🇷 阿根廷接入",
    "[]🇧🇷 巴西接入",
    "[]🏳️‍🌈 IPV6线路",
    "[]🇨🇳 回国线路",
]

[[custom_groups]]
name = "🎥 TikTok"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]🎯 全部直连",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
    "[]🇮🇳 印度接入",
    "[]🇬🇧 英国接入",
    "[]🇫🇷 法国接入",
    "[]🇨🇦 加拿大接入",
    "[]🇦🇺 澳大利亚接入",
    "[]🇮🇪 爱尔兰接入",
    "[]🇷🇺 俄罗斯接入",
    "[]🇹🇷 土耳其接入",
    "[]🇦🇷 阿根廷接入",
    "[]🇧🇷 巴西接入",
    "[]🏳️‍🌈 IPV6线路",
    "[]🇨🇳 回国线路",
]

[[custom_groups]]
name = "🌍 国外媒体"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]🎯 全部直连",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
    "[]🇮🇳 印度接入",
    "[]🇬🇧 英国接入",
    "[]🇫🇷 法国接入",
    "[]🇨🇦 加拿大接入",
    "[]🇦🇺 澳大利亚接入",
    "[]🇮🇪 爱尔兰接入",
    "[]🇷🇺 俄罗斯接入",
    "[]🇹🇷 土耳其接入",
    "[]🇦🇷 阿根廷接入",
    "[]🇧🇷 巴西接入",
    "[]🏳️‍🌈 IPV6线路",
    "[]🇨🇳 回国线路",
]

[[custom_groups]]
name = "🎵 网易云音乐"
type = "select"
rule = [
    "[]🎯 全部直连",
    "[]🔰 节点选择",
    "[]✈️ 手动选择",
    "[]🇨🇳 回国线路",
]

[[custom_groups]]
name = "🌍 国内媒体-港澳台版切换"
type = "select"
rule = [
    "[]🌏 国内媒体",
    "[]🎯 全部直连",
    "[]🔰 节点选择",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇨🇳 回国线路",
]

[[custom_groups]]
name = "🌏 国内媒体"
type = "select"
rule = [
    "[]🎯 全部直连",
    "[]🔰 节点选择",
    "[]✈️ 手动选择",
    "[]🇨🇳 回国线路",
]

[[custom_groups]]
name = "📲 Telegram"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]🎯 全部直连",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
    "[]🇮🇳 印度接入",
    "[]🇬🇧 英国接入",
    "[]🇫🇷 法国接入",
    "[]🇨🇦 加拿大接入",
    "[]🇦🇺 澳大利亚接入",
    "[]🇮🇪 爱尔兰接入",
    "[]🇷🇺 俄罗斯接入",
    "[]🇹🇷 土耳其接入",
    "[]🇦🇷 阿根廷接入",
    "[]🇧🇷 巴西接入",
    "[]🏳️‍🌈 IPV6线路",
    "[]🇨🇳 回国线路",
]

[[custom_groups]]
name = "📲 Twitter"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]🎯 全部直连",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
    "[]🇮🇳 印度接入",
    "[]🇬🇧 英国接入",
    "[]🇫🇷 法国接入",
    "[]🇨🇦 加拿大接入",
    "[]🇦🇺 澳大利亚接入",
    "[]🇮🇪 爱尔兰接入",
    "[]🇷🇺 俄罗斯接入",
    "[]🇹🇷 土耳其接入",
    "[]🇦🇷 阿根廷接入",
    "[]🇧🇷 巴西接入",
    "[]🏳️‍🌈 IPV6线路",
    "[]🇨🇳 回国线路",
]

# [[custom_groups]]
# name = "📞 虚拟电话"
# type = "select"
# rule = [
#     "[]🎯 全部直连",
#     "[]🔰 节点选择",
#     "[]✈️ 手动选择",
#     "[]🇭🇰 香港接入",
#     "[]🇺🇸 美国接入",
#     "[]🇯🇵 日本接入",
#     "[]🇨🇳 台湾接入",
#     "[]🇸🇬 新加坡接入",
#     "[]🇰🇷 韩国接入",
#     "[]🇮🇳 印度接入",
#     "[]🇬🇧 英国接入",
#     "[]🇫🇷 法国接入",
#     "[]🇨🇦 加拿大接入",
#     "[]🇦🇺 澳大利亚接入",
#     "[]🇮🇪 爱尔兰接入",
#     "[]🇷🇺 俄罗斯接入",
#     "[]🇹🇷 土耳其接入",
#     "[]🇦🇷 阿根廷接入",
#     "[]🇧🇷 巴西接入",
#     "[]🏳️‍🌈 IPV6线路",
#     "[]🇨🇳 回国线路",
# ]

[[custom_groups]]
name = "🎯 全部直连"
type = "select"
rule = ["[]DIRECT"]

[[custom_groups]]
name = "🛑 全部拦截"
type = "select"
rule = ["[]REJECT"]

[[custom_groups]]
name = "🐟 漏网之鱼"
type = "select"
rule = [
    "[]🔰 节点选择",
    "[]🎯 全部直连",
    "[]✈️ 手动选择",
    "[]🇭🇰 香港接入",
    "[]🇺🇸 美国接入",
    "[]🇯🇵 日本接入",
    "[]🇨🇳 台湾接入",
    "[]🇸🇬 新加坡接入",
    "[]🇰🇷 韩国接入",
    "[]🇮🇳 印度接入",
    "[]🇬🇧 英国接入",
    "[]🇫🇷 法国接入",
    "[]🇨🇦 加拿大接入",
    "[]🇦🇺 澳大利亚接入",
    "[]🇮🇪 爱尔兰接入",
    "[]🇷🇺 俄罗斯接入",
    "[]🇹🇷 土耳其接入",
    "[]🇦🇷 阿根廷接入",
    "[]🇧🇷 巴西接入",
    "[]🏳️‍🌈 IPV6线路",
    "[]🇨🇳 回国线路",
]

