# [[custom_groups]]
# name = "ğŸ­ æœåŠ¡åç§°"
# type = "select"
# rule = [
#     "[]âœˆï¸ æ‰‹åŠ¨é€‰æ‹©",
#     "[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
#     "[]ğŸ¯ å…¨éƒ¨ç›´è¿",
#     "[]ğŸ‡­ğŸ‡° é¦™æ¸¯æ¥å…¥",
#     "[]ğŸ‡ºğŸ‡¸ ç¾å›½æ¥å…¥",
#     "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬æ¥å…¥",
#     "[]ğŸ‡¨ğŸ‡³ å°æ¹¾æ¥å…¥",
#     "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡æ¥å…¥",
#     "[]ğŸ‡°ğŸ‡· éŸ©å›½æ¥å…¥",
#     "[]ğŸ‡®ğŸ‡³ å°åº¦æ¥å…¥",
#     "[]ğŸ‡¬ğŸ‡§ è‹±å›½æ¥å…¥",
#     "[]ğŸ‡«ğŸ‡· æ³•å›½æ¥å…¥",
#     "[]ğŸ‡¨ğŸ‡¦ åŠ æ‹¿å¤§æ¥å…¥",
#     "[]ğŸ‡¦ğŸ‡º æ¾³å¤§åˆ©äºšæ¥å…¥",
#     "[]ğŸ‡®ğŸ‡ª çˆ±å°”å…°æ¥å…¥",
#     "[]ğŸ‡·ğŸ‡º ä¿„ç½—æ–¯æ¥å…¥",
#     "[]ğŸ‡¹ğŸ‡· åœŸè€³å…¶æ¥å…¥",
#     "[]ğŸ‡¦ğŸ‡· é˜¿æ ¹å»·æ¥å…¥",
#     "[]ğŸ‡§ğŸ‡· å·´è¥¿æ¥å…¥",
#     "[]ğŸ³ï¸â€ğŸŒˆ IPV6çº¿è·¯",
#     "[]ğŸ‡¨ğŸ‡³ å›å›½çº¿è·¯",
# ]

# [[custom_groups]]
# name = "â™»ï¸ è‡ªåŠ¨é€‰æ‹©"
# type = "url-test"
# rule = [".*"]
# url = "http://www.gstatic.com/generate_204"
# interval = 300

# How to:
# 1. Replace "airportName" to what you want.
# 2. Replace "tagName" to what you have set in config.
# 3. Comment/delete the areas you don't need.

[[custom_groups]]
name = "âœˆï¸ airportName"
type = "select"
rule = [
    "[]ğŸ‡­ğŸ‡° airportName HK",
    "[]ğŸ‡ºğŸ‡¸ airportName US",
    "[]ğŸ‡¯ğŸ‡µ airportName JP",
    "[]ğŸ‡¨ğŸ‡³ airportName TW",
    "[]ğŸ‡¸ğŸ‡¬ airportName SG",
    "[]ğŸ‡°ğŸ‡· airportName KR",
    "[]ğŸ‡®ğŸ‡³ airportName IN",
    "[]ğŸ‡¬ğŸ‡§ airportName UK",
    "[]ğŸ‡«ğŸ‡· airportName FR",
    "[]ğŸ‡¨ğŸ‡¦ airportName CA",
    "[]ğŸ‡¦ğŸ‡º airportName AU",
    "[]ğŸ‡¹ğŸ‡· airportName TR",
    "[]ğŸ‡¦ğŸ‡· airportName AR",
    "[]ğŸ‡§ğŸ‡· airportName BR",
    "[]ğŸ³ï¸â€ğŸŒˆ airportName IPV6",
    "[]ğŸ‡¨ğŸ‡³ airportName CN",
    "!!GROUP=tagName",
]

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° airportName HK"
type = "url-test"
rule = ["!!GROUP=tagName!!(?i:\\bHK[G]?\\b|Hong.*?Kong|\\bHKT\\b|\\bHKBN\\b|\\bHGC\\b|\\bWTT\\b|\\bCMI\\b|[^-]æ¸¯)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡ºğŸ‡¸ airportName US"
type = "url-test"
rule = ["!!GROUP=tagName!!(?i:\\bUS[A]?\\b|America|United.*?States|ç¾å›½|[^-]ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡¯ğŸ‡µ airportName JP"
type = "url-test"
rule = ["!!GROUP=tagName!!(?i:\\bJP[N]?\\b|Japan|Tokyo|Osaka|Saitama|æ—¥æœ¬|ä¸œäº¬|å¤§é˜ª|åŸ¼ç‰|[^-]æ—¥)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡¨ğŸ‡³ airportName TW"
type = "url-test"
rule = ["!!GROUP=tagName!!(?i:\\bTW[N]?\\b|Taiwan|æ–°åŒ—|å½°åŒ–|\\bCHT\\b|å°æ¹¾|[^-]å°|\\bHINET\\b)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ airportName SG"
type = "url-test"
rule = ["!!GROUP=tagName!!(?i:\\bSG[P]?\\b|Singapore|æ–°åŠ å¡|ç‹®åŸ|[^-]æ–°)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡°ğŸ‡· airportName KR"
type = "url-test"
rule = ["!!GROUP=tagName!!(?i:\\bK[O]?R\\b|Korea|é¦–å°”|éŸ©|éŸ“)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡®ğŸ‡³ airportName IN"
type = "url-test"
rule = ["!!GROUP=tagName!!(?i:\\bIN[D]?\\b|India|Mumbai|å°åº¦|å­Ÿä¹°|åŠ å°”å„ç­”|è´¾åå¾·|æ³°ç±³å°”çº³å¾·)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡¬ğŸ‡§ airportName UK"
type = "url-test"
rule = ["!!GROUP=tagName!!(?i:\\bUK\\b|\\bGB[R]?\\b|England|United.*?Kingdom|London|è‹±å›½|[^-]è‹±|ä¼¦æ•¦)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡«ğŸ‡· airportName FR"
type = "url-test"
rule = ["!!GROUP=tagName!!(?i:\\bFR[A]?\\b|France|Paris|æ³•å›½|å·´é»)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡¨ğŸ‡¦ airportName CA"
type = "url-test"
rule = ["!!GROUP=tagName!!(?i:\\bCA[N]?\\b|Canada|Toronto|Montreal|Vancouver|åŠ æ‹¿å¤§|è’™ç‰¹åˆ©å°”|æ¸©å“¥å|æ¥“è‘‰|æ«å¶)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡¦ğŸ‡º airportName AU"
type = "url-test"
rule = ["!!GROUP=tagName!!(?i:\\bAU[S]?\\b|Australia|Sydney|æ¾³å¤§åˆ©äºš|æ¾³æ´²|æ‚‰å°¼)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡®ğŸ‡ª airportName IE"
type = "url-test"
rule = ["!!GROUP=tagName!!(Ireland|Dublin|çˆ±å°”å…°|éƒ½æŸæ—)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡·ğŸ‡º airportName RU"
type = "url-test"
rule = ["!!GROUP=tagName!!(?i:\\bRU[S]?\\b|Russia|Moscow|Petersburg|Siberia|ä¼¯åŠ›|è«æ–¯ç§‘|åœ£å½¼å¾—å ¡|è¥¿ä¼¯åˆ©äºš|æ–°è¥¿ä¼¯åˆ©äºš|å“ˆå·´ç½—å¤«æ–¯å…‹|ä¿„ç½—æ–¯|[^-]ä¿„)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡¹ğŸ‡· airportName TR"
type = "url-test"
rule = ["!!GROUP=tagName!!(Turkey|åœŸè€³å…¶|ä¼Šæ–¯å¦å¸ƒå°”)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡¦ğŸ‡· airportName AR"
type = "url-test"
rule = ["!!GROUP=tagName!!(Argentina|é˜¿æ ¹å»·)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡§ğŸ‡· airportName BR"
type = "url-test"
rule = ["!!GROUP=tagName!!(Brazil|Paulo|å·´è¥¿|åœ£ä¿ç½—)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ³ï¸â€ğŸŒˆ airportName IPV6"
type = "url-test"
rule = ["!!GROUP=tagName!!(ipv6|IPV6)"]
url = "http://www.gstatic.com/generate_204"
interval = 300

[[custom_groups]]
name = "ğŸ‡¨ğŸ‡³ airportName CN"
type = "url-test"
rule = ["!!GROUP=tagName!!(?i:\\bC[H]?N\\b|China|å›å›½|ä¸­å›½[^-]|æ±Ÿè‹[^-]|åŒ—äº¬[^-]|ä¸Šæµ·[^-]|å¹¿å·[^-]|æ·±åœ³[^-]|æ­å·[^-]|å¸¸å·[^-]|å¾å·[^-]|é’å²›[^-]|å®æ³¢[^-]|é•‡æ±Ÿ[^-]|æˆéƒ½[^-]|back)"]
url = "http://www.gstatic.com/generate_204"
interval = 300